### ISSUE TITLE
安装adapter后会出现sqlite报错

### ISSUE THREAD

**Issue by assassinliujie** [koishijs/koishi-plugin-adapter-onebot#26]
sqlite auto migrating table user
2024-04-26 02:39:10 [W] sqlite > CREATE TABLE `user_temp` (`id` undefined NOT NULL PRIMARY KEY AUTOINCREMENT, `name` undefined NULL, `flag` undefined NULL DEFAULT 0, `authority` undefined NULL DEFAULT 0, `locales` undefined NULL DEFAULT '[]', `permissions` undefined NULL DEFAULT '[]', `createdAt` undefined NULL, `usage` undefined NULL DEFAULT '{}', `timers` undefined NULL DEFAULT '{}') []
2024-04-26 02:39:10 [I] sqlite auto migrating table binding
2024-04-26 02:39:10 [I] sqlite auto migrating table channel
2024-04-26 02:39:10 [I] sqlite auto migrating table analytics.message
2024-04-26 02:39:10 [I] sqlite auto migrating table analytics.command
2024-04-26 02:39:10 [W] app Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] app Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] app Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)
2024-04-26 02:39:11 [W] console Error: AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY
                            at f.handleError (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:90:53)
                            at f.prepare (/koishi/node_modules/@minatojs/sql.js/dist/sql-wasm.js:88:312)
                            at #exec (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:312:28)
                            at #run (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:340:15)
                            at SQLiteDriver.prepare (/koishi/node_modules/@minatojs/driver-sqlite/lib/index.cjs:246:16)
                            at Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:810:18)
                            at async Proxy.prepare (/koishi/node_modules/minato/lib/index.cjs:801:5)

**Comment by luolinlin768** [comment]
一样遇到该问题，并且尝试安装旧版本插件也是同样的报错（docker部署的）

**Comment by assassinliujie** [comment]
> 一样遇到该问题，并且尝试安装旧版本插件也是同样的报错（docker部署的）

更新sqlite依赖到最新就好了，你看看插件里有个sqlite的
