### ISSUE TITLE
Bug: Koishi 更新后onebot依赖报错

### ISSUE THREAD

**Issue by TszcWhut** [koishijs/koishi-plugin-adapter-onebot#29]
```
config failed to load adapter-onebot
2024-06-04 09:58:45 [W] config /koishi/node_modules/koishi-plugin-adapter-onebot/lib/index.js:1
                        import { OneBotBot } from './bot';
                        ^^^^^^
                        
                        SyntaxError: Cannot use import statement outside a module
                            at wrapSafe (node:internal/modules/cjs/loader:1281:20)
                            at Module._compile (node:internal/modules/cjs/loader:1321:27)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
                            at Module.load (node:internal/modules/cjs/loader:1208:32)
                            at Module._load (node:internal/modules/cjs/loader:1024:12)
                            at Module.require (node:internal/modules/cjs/loader:1233:19)
                            at require (node:internal/modules/helpers:179:18)
                            at Proxy.import (/koishi/node_modules/@koishijs/loader/lib/index.js:182:12)
                            at Proxy.resolve (/koishi/node_modules/@koishijs/loader/lib/shared.js:267:51)
                            at Proxy.parseExports (/koishi/node_modules/@koishijs/plugin-config/lib/shared/index.js:88:45)
```

**Comment by TszcWhut** [comment]
删除容器 0插件重新部署后，在单独安装onebot时也报错，与4.17.8不兼容

**Comment by Starrain08** [comment]
加一，onebot适配器降级到6.5.4就没有此问题
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/119772101/ea14fb25-d57e-4102-aa31-3d80a716fa9a)
![image](https://github.com/koishijs/koishi-plugin-adapter-onebot/assets/119772101/8c684f4f-66b3-4b53-a5e8-7ff74d342723)

**Comment by shigma** [comment]
感谢反馈。请尝试使用 6.5.6 版本。

**Comment by TszcWhut** [comment]
新版似乎移除了登录状态显示，请问以后还会加回来吗？

**Comment by shigma** [comment]
如果你的登录状态显示有问题，可以另开一个 issue。

**Comment by Starrain08** [comment]
> 新版似乎移除了登录状态显示，请问以后还会加回来吗？

状态显示跑到status插件那里显示了

**Comment by shigma** [comment]
这应该是一个 status 插件的 bug。
