### ISSUE TITLE
发送私聊消息（图片）时出现报错，但还是正常发送出消息

### ISSUE THREAD

**Issue by axlmly** [koishijs/koishi-plugin-adapter-onebot#32]
onebot版本6.5.8
koishi4.17.8
发送私聊正常发送，但会报错
2024-06-12 21:44:24 [W] session Error: Error with request send_private_msg, args: {"user_id":1206147964,"message":[{"type":"image","data":{"file":"file:///D:/Gallery/ComicNyaa/%E5%A1%97%E9%B4%89_109731181_p8.jpg","cache":0}}]}, retcode: 1200
                            at _Internal._get (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:160:20)
                            at async OneBotMessageEncoder.flush (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:780:227)
                            at async OneBotMessageEncoder.send (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:610:5)
                            at async Proxy.sendMessage (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:340:22)
                            at async C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2190:7
                            at async Proxy.withScope (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2087:22)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:890:16)
                            at async next (C:\Users\xiuzh\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:890:16)

**Comment by shigma** [comment]
图片是不是就发不出来了，只能发文本？

**Comment by axlmly** [comment]
> 图片是不是就发不出来了，只能发文本？

可以发送，但只有发图片时会出现报错

**Comment by 250king** [comment]
也有相同的错误，重启过后会好，但继续运行一段时间就会报错

**Comment by 250king** [comment]
但现在重启也有问题了……
```
2024-06-15 13:11:44 [W] market Error: request timeout
                            at Timeout.<anonymous> (/root/app/Koishi/data/instances/default/node_modules/@cordisjs/plugin-http/lib/index.cjs:301:26)
                            at listOnTimeout (node:internal/timers:573:17)
                            at process.processTimers (node:internal/timers:514:7)
2024-06-15 13:11:56 [W] session Error: Error with request send_private_msg, args: {"user_id":2789260300,"message":[{"type":"image","data":{"file":"https://github.com/ElainaFanBoy/nonebot_plugin_githubcard","cache":0}}]}, retcode: 1200
                            at _Internal._get (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:780:227)
                            at async OneBotMessageEncoder.send (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:610:5)
                            at async Proxy.sendMessage (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:340:22)
2024-06-15 13:12:54 [W] session Error: Error with request send_private_msg, args: {"user_id":2789260300,"message":[{"type":"image","data":{"file":"https://github.com/ElainaFanBoy/nonebot_plugin_githubcard/pull/3","cache":0}}]}, retcode: 1200
                            at _Internal._get (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:780:227)
                            at async OneBotMessageEncoder.send (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:610:5)
                            at async Proxy.sendMessage (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:340:22)
2024-06-15 13:13:24 [W] session Error: Error with request send_private_msg, args: {"user_id":2789260300,"message":[{"type":"image","data":{"file":"https://github.com/ElainaFanBoy/nonebot_plugin_githubcard/pull/3","cache":0}}]}, retcode: 1200
                            at _Internal._get (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/root/app/Koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:780:227)
                            at async OneBotMessageEncoder.send (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:610:5)
                            at async Proxy.sendMessage (/root/app/Koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:340:22)
```

**Comment by shigma** [comment]
这两个问题均不是 Koishi 或者 adapter onebot 的问题。

第一个报错中的链接是 `file:///D:/Gallery/ComicNyaa/%E5%A1%97%E9%B4%89_109731181_p8.jpg`，这完全遵循 OneBot v11 标准。请检查这个文件是否在本地存在，如果存在可以前往你的 OneBot 实现侧提交 issue。

参考：https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%9B%BE%E7%89%87

第二个报错中的链接是 `https://github.com/ElainaFanBoy/nonebot_plugin_githubcard/pull/3`，这显然不是一个图片链接。请检查你的插件实现。
