### ISSUE TITLE
6.5.9 含图片的消息发送失败

### ISSUE THREAD

**Issue by manipEgo** [koishijs/koishi-plugin-adapter-onebot#39]
描述：

在使用插件 [koishi-plugin-whateat-pic](https://www.npmjs.com/package/koishi-plugin-whateat-pic/v/1.1.4) 时产生警告，机器人没有正常发送包含图片的消息。对接平台 QQ，所有依赖最新。

该问题在将 adapter-onebot 回退至 `6.5.8` 后解决。仓库里版本更新比较跳跃，我没有尝试向下定位问题原因。

使用上述插件应该可以稳定复现。

log:

```
[W] session Error: Error with request send_private_msg, args: {"user_id":,"message":[{"type":"reply","data":{"id":""}},{"type":"text","data":{"text":"推荐你吃：\n✨韩式烤肉✨"}},{"type":"image","data":{"file":".koishi/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/eat_pic/韩式烤肉.jpg","cache":0}}]}, retcode: 200
                            at _Internal._get (/.koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendPrivateMsg] (/.koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:160:20)
                            at async OneBotMessageEncoder.flush (/.koishi/data/instances/default/node_modules/koishi-plugin-adapter-onebot/lib/index.js:781:227)
                            at async OneBotMessageEncoder.send (/.koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:616:5)
                            at async Proxy.sendMessage (/.koishi/data/instances/default/node_modules/@satorijs/core/lib/index.cjs:346:22)
                            at async /.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:2172:7
                            at async Proxy.withScope (/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:2069:22)
                            at async /.koishi/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/index.js:62:20
                            at async next (/.koishi/data/instances/default/node_modules/@koishijs/core/lib/index.cjs:857:16)
```

**Comment by shigma** [comment]
6.5.11

已回退此更新，感谢反馈。

**Comment by TheFairyTale** [comment]
您好, 我看目前最新版onebot 插件(6.5.11)又出现这个错误了：
试了下回退到6.5.8 也还有这个错
6.5.11版本的报错
```
Error: Error with request send_group_msg, args: 
{"group_id":812428549,"message":[{"type":"reply","data":{"id":"188607583"}},{"type":"text","data":{"text":"湊あくあ（本物）推荐你吃：\n✨牛肉粉✨"}},{"type":"image","data":{"file":"file:///C:/Users/Administrator/AppData/Roaming/Koishi/Desktop/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/eat_pic/%E7%89%9B%E8%82%89%E7%B2%89.jpg","cache":0}}]}, retcode: 200
```
6.5.8版本的报错：
```
2024-08-08 14:33:06 [W] session Error: Error with request send_group_msg, args: {"group_id":937121513,"message":[{"type":"reply","data":{"id":"-1404270705"}},{"type":"text","data":{"text":"湊あくあ（本物）推荐你吃：\n✨葱油拌面✨"}},{"type":"image","data":{"file":"file:///C:/Users/Administrator/AppData/Roaming/Koishi/Desktop/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/eat_pic/%E8%91%B1%E6%B2%B9%E6%8B%8C%E9%9D%A2.jpg","cache":0}}]}, retcode: 200
                            at _Internal._get (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:120:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:160:20)
                            at async OneBotMessageEncoder.flush (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:780:330)
                            at async OneBotMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:616:5)
                            at async Proxy.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
                            at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
                            at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
                            at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
```


whateat-pic 插件版本 1.1.4 (https://www.npmjs.com/package/koishi-plugin-whateat-pic/v/1.1.4)

Koishi环境：
System:
    OS: Windows Server 2016 10.0.14393
    CPU: (6) x64 AMD FX(tm)-8300 Eight-Core Processor           
Binaries:
    Node: 20.12.2
    Yarn: 4.1.1
Koishi:
    Core: 4.17.10
    Console: 5.28.4
    Koishi Desktop: 1.1.3

OneBot版本及系统环境:
    OneBot 实现：https://github.com/LagrangeDev/Lagrange.Core               （Lagrange.OneBot_linux-x64_net8.0_SelfContained.tar.gz）
    Linux服务器: Ubuntu 22.04 jammy
    Kernel: x86_64 Linux 6.2.0-1017-aws

**Comment by TheFairyTale** [comment]
> 您好, 我看目前最新版onebot 插件(6.5.11)又出现这个错误了： 试了下回退到6.5.8 也还有这个错 6.5.11版本的报错
> 
> ```
> Error: Error with request send_group_msg, args: 
> {"group_id":812428549,"message":[{"type":"reply","data":{"id":"188607583"}},{"type":"text","data":{"text":"湊あくあ（本物）推荐你吃：\n✨牛肉粉✨"}},{"type":"image","data":{"file":"file:///C:/Users/Administrator/AppData/Roaming/Koishi/Desktop/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/eat_pic/%E7%89%9B%E8%82%89%E7%B2%89.jpg","cache":0}}]}, retcode: 200
> ```
> 
> 6.5.8版本的报错：
> 
> ```
> 2024-08-08 14:33:06 [W] session Error: Error with request send_group_msg, args: {"group_id":937121513,"message":[{"type":"reply","data":{"id":"-1404270705"}},{"type":"text","data":{"text":"湊あくあ（本物）推荐你吃：\n✨葱油拌面✨"}},{"type":"image","data":{"file":"file:///C:/Users/Administrator/AppData/Roaming/Koishi/Desktop/data/instances/default/node_modules/koishi-plugin-whateat-pic/lib/eat_pic/%E8%91%B1%E6%B2%B9%E6%8B%8C%E9%9D%A2.jpg","cache":0}}]}, retcode: 200
>                             at _Internal._get (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:120:11)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>                             at async _Internal.<computed> [as sendGroupMsg] (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:160:20)
>                             at async OneBotMessageEncoder.flush (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-adapter-onebot\lib\index.js:780:330)
>                             at async OneBotMessageEncoder.send (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:616:5)
>                             at async Proxy.sendMessage (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:346:22)
>                             at async C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2172:7
>                             at async Proxy.withScope (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:2069:22)
>                             at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
>                             at async next (C:\Users\Administrator\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@koishijs\core\lib\index.cjs:857:16)
> ```
> 
> whateat-pic 插件版本 1.1.4 (https://www.npmjs.com/package/koishi-plugin-whateat-pic/v/1.1.4)
> 
> Koishi环境： System: OS: Windows Server 2016 10.0.14393 CPU: (6) x64 AMD FX(tm)-8300 Eight-Core Processor Binaries: Node: 20.12.2 Yarn: 4.1.1 Koishi: Core: 4.17.10 Console: 5.28.4 Koishi Desktop: 1.1.3
> 
> OneBot版本及系统环境: OneBot 实现：https://github.com/LagrangeDev/Lagrange.Core （Lagrange.OneBot_linux-x64_net8.0_SelfContained.tar.gz） Linux服务器: Ubuntu 22.04 jammy Kernel: x86_64 Linux 6.2.0-1017-aws

@shigma

**Comment by shigma** [comment]
之前的报错是 onebot 发送的请求有误所致。新的报错中看不出请求有问题，我觉得你可能需要找一下其他原因。

比如测试一下只发送文本有没有报错？
